server:
  port: 9998
  servlet:
    context-path: /shirotest
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/comment_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRUnMillis: 60000
    minEvictableIdeleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters:
    commons-log.connection-logger-name: stat,wall,log4j
    useGlobalDataSourceStat: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.lzh.shirospringboot.pojo
